### ISSUE TITLE
Year attribute missing

### ISSUE THREAD

**Issue by vella9** [MoojMidge/service.upnext#37]
Hi @MoojMidge, I just noticed that using the latest master.zip provided, the Year is missing as per screenshot. This should be before the rating.

![image](https://github.com/user-attachments/assets/2fcd0a18-2c14-4277-895c-f3b90b7166be)

**Comment by MoojMidge** [comment]
Give https://github.com/MoojMidge/service.upnext/archive/refs/heads/master.zip a go - should be fixed.

**Comment by vella9** [comment]
sorry @MoojMidge but Year is still not showing after testing on this version.

**Comment by MoojMidge** [comment]
Can you get a log? I had a look in one of the older logs you uploaded previously, but the information being returned by the TMDbHelper integration may not be consistent.

Also is there any difference if you disable `UpNext > Settings > Appearance > Skin customisation > Apply Kodi skin to UpNext popup`

**Comment by MoojMidge** [comment]
Never mind about the log - I can replicate the problem. Should be easy to fix.

**Comment by MoojMidge** [comment]
Try https://github.com/MoojMidge/service.upnext/archive/refs/heads/master.zip again

**Comment by vella9** [comment]
> Try https://github.com/MoojMidge/service.upnext/archive/refs/heads/master.zip again

Hi @MoojMidge, this now worked as per below. Thank You! 
However it is displaying the whole date and not just the Year. Not sure if this is intended. 

![image](https://github.com/user-attachments/assets/39f270a6-00fe-4775-ac52-0830255a362b)

Thanks again!

**Comment by MoojMidge** [comment]
> However it is displaying the whole date and not just the Year. Not sure if this is intended.

Yes, that's intended.

It wasn't like that in the original plugin, but year by itself is not that useful for episodes, so the year property is overwritten for episodes to show the full date.

Year is still shown for movies, and will probably still show up for episodes in skins like Arctic Hoeizon 2 and Arctic Fuse that show their own popup via the OSD, when not using this plugin.
