### ISSUE TITLE
upnext show same popup as what am watching

### ISSUE THREAD

**Issue by Peter3344** [MoojMidge/service.upnext#48]
after updating both tmdb and upnext latest update when i play an episode and upnext popup its popup same episode am watching 
in this debug log am watching the last of us s2e2 and upnext popup s2e2
i dont know where to report this issue here or @jurialmunkey 

here a debug log 

[https://paste.kodi.tv/axuwibareq.kodi](https://paste.kodi.tv/axuwibareq.kodi)

Thank you

**Comment by MoojMidge** [comment]
The reason the same episode popped up is becuase the same episode was added 6 times to the current playlist.

You have the option to `Queue all next episoded` enabled, and there are 5 episodes of the show after the 2nd episode, so for whatever reason it seems like the `get_next_episodes` method is not working in the same way it used to.

This could be because of a change in the newer versions of TMDbHelper that this addon has not taken into account, or a bug in TMDbHelper.

There have been some reports of some episodes having the season and episode missing in the newer version of TMDbHelper, but I haven't looked into it. It could be that if this is the case, the database queries used by TMDbHelper are just returning the same episode that was cached in the database, because it does have the season and episode number provided, while the other episodes are defaulting to a season and episode number of `-1` and are therefore not being matched. Just speculating.

jurialmunkey has made a lot of improvements and changes, but seems to be getting quite a bit of undeserved flak about it at the moment. There is no need to trouble him about this as the use of TMDbHelper in UpNext was always experimental with functionality provided as-is by TMDbHelper.

Suggest disabling `Queue all next episoded` for the time being and seeing if that works, until I have more time to look into it.

**Comment by jurialmunkey** [comment]
> so for whatever reason it seems like the get_next_episodes method is not working in the same way it used to.

@MoojMidge - I have a feeling this likely is the case, as the playlist creation is not usually something I rely on myself and there is every chance I've unintentionally broken it. (I did make a note to myself that in particular I did need to revisit this block of code).

Are you calling the Player class' method for get_next_episodes? or is just the function in lib.player.details ? I'll try to have a look in the next couple of days because I'm sure I it's just a case of I've overlooked a small detail in connecting it up to new database.

**Comment by jurialmunkey** [comment]
Think this should fix it: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/ef8d56ff66134c38517fe9e8cc13de05c3e3dc31

At least it seems to be returning the correct ListItem objects when testing manually, so it should work. 

I wasn't 100% on whether it returned a list of xbmcgui.ListItem objects or just TMDbHelper item objects originally, but fairly sure it is meant to return ListItem objects which is what it is doing currently.

**Comment by Peter3344** [comment]
Hello @jurialmunkey thank you for your great work i just tested the playlist appeared correctly but I upnext still broken and I got an error in my log 

[log](https://paste.kodi.tv/genefeciba.kodi)

**Comment by jurialmunkey** [comment]
> Hello [@jurialmunkey](https://github.com/jurialmunkey) thank you for your great work i just tested the playlist appeared correctly but I upnext still broken and I got an error in my log
> 
> [log](https://paste.kodi.tv/genefeciba.kodi)

Thanks for the log.

It looks like the upnext service attempts to call the `get_tmdb_id` method on the `TMDb` class. Problem is that this method no longer exists as it is now part of a database class.

Without testing, this commit https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/46bf37256cc9f68344cdbb525818095b8102bfb4 should monkey patch it to make it compatible.

**Comment by Peter3344** [comment]
Yes working great now thank you so  much

**Comment by MoojMidge** [comment]
@jurialmunkey - thanks for looking into this, but please don't feel that you need to make changes to TMDbHelper to suit this addon.

I remember you explicitly cited such a scenario as a reason why you were hesitant to add the code required to make TMDbHelper importable, and my response at that time was that if any upstream changes are made then it is the responsibility of downstream to follow suit.

Still intend to stick to that, so unless there is an actual issue in TMDbHelper, feel free to ignore what this addon may require when importing TMDbHelper
